name: solq
description: SOLQ Payment Orchestrator
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  http: ^1.1.0
  provider: ^6.0.5
  solana: ^0.32.0
  intl: ^0.18.1
  uuid: ^4.0.0
  url_launcher: ^6.2.1
  app_links: ^3.5.0
  shared_preferences: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  bs58: ^1.0.2
  crypto: ^3.0.3
  characters: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
